from enum import Enum


class PromptFeatures(Enum):
    CODE_QUERY_SOLVER = "CODE_QUERY_SOLVER"
    SESSION_SUMMARY_GENERATOR = "SESSION_SUMMARY_GENERATOR"
    INLINE_EDITOR = "INLINE_EDITOR"
    TERMINAL_COMMAND_EDITOR = "TERMINAL_COMMAND_EDITOR"
