-- migrate:up
ALTER TABLE SESSION_CHATS ADD COLUMN RESPONSE_SUMMARY VARCHAR;
ALTER TABLE SESSION_CHATS ADD COLUMN USER_QUERY VARCHAR NOT NULL DEFAULT '';

-- migrate:down
ALTER TABLE SESSION_CHATS DROP COLUMN USER_QUERY;
ALTER TABLE SESSION_CHATS DROP COLUMN RESPONSE_SUMMARY;
