X_HEADERS = "X-HEADERS"
X_SHARED_CONTEXT = "X-SHARED-CONTEXT"

X_REQUEST_ID = "X-REQUEST-ID"
X_VISITOR_ID = "X-VISITOR-ID"

X_SOURCE_IP = "X-SOURCE-IP"
X_SOURCE_USER_AGENT = "X-SOURCE-USER-AGENT"
X_SOURCE_REFERER = "X-SOURCE-REFERER"
X_SERVICE_NAME = "X-SERVICE-NAME"
X_SERVICE_VERSION = "X-SERVICE-VERSION"

X_USER_AGENT = "X-USER-AGENT"
USER_AGENT = "User-Agent"

CONTENT_TYPE = "Content-Type"
ACCEPT = "Accept"

GLOBAL_HEADERS = "global_headers"
