image: "python:3.7"
before_script:
  - python --version
  - pip install -r requirements/test.txt
  - cp config_template.json config.json
stages:
  - Static Analysis
  - Test
pylint:
  stage: Static Analysis
  script:
  - pylint app/
