repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4  # replace with the latest if needed
    hooks:
    # Run the linter with --fix.
    - id: ruff
      args: [--fix]
    # Run the formatter.
    - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.3
    hooks:
      - id: uv-lock