image: python:3.9

pipelines:
  pull-requests:
    'hotfix/*':
      - step:
          name: Skip bitbucket pipeline
          script:
            - echo "Skipping bitbucket pipeline for this branch"
    '**': #this runs as default for any branch not elsewhere defined
      - parallel:
          fail-fast: true
          steps:
            - step:
                name: Black Formatter Check
                script:
                  - pip install black=="22.3.0"
                  # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
                  - black app/ --check
            - step:
                name: isort Check
                script:
                  - pip install isort=="5.10.1"
                  - isort app/ --check --profile black
            - step:
                name: Flake8 Check
                script:
                  - pip install flake8=="4.0.1"
                  - flake8 app/ --show-source --statistics
