title = "DeputyDev configuration"

[app]
name = "deputy_dev"
description = ""
language = "python:3.9"
framework = "sanic"
owner = ""

[code_review_agent]
enable = true                       # Set to true to enable the code review agent, false to disable
is_override = true                 # Set to true if this configuration can be overridden by repo level configuration
model = "claude_3.5_sonnet"         # Specifying which model to use for code reviews
exclusions = []
inclusions = []

[code_review_agent.agents.security]
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.9              # Threshold of confidence_score for a comment to qualify to be made on PR

[code_review_agent.agents.code_communication]
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.98

[code_review_agent.agents.performance_optimisation]
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.9

[code_review_agent.agents.code_maintainability]
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.9

[code_review_agent.agents.error]
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.9

[code_review_agent.agents.business_logic_validation]
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.9

[chat]
enable = false
model = "gpt-4o"
is_override = true
custom_prompt = ""

[pr_summary]
enable = true
model = "gpt-4o"
is_override = true
custom_prompt = ""
