title = "DeputyDev configuration"

[app]
name = "deputy_dev"
description = ""
language = "python:3.9"
framework = "sanic"
owner = ""

[code_review_agent]
enable = true                       # Set to true to enable the code review agent, false to disable
is_override = true                 # Set to true if this configuration can be overridden by repo level configuration
model = "claude_3.5_sonnet"         # Specifying which model to use for code reviews
exclusions = []
inclusions = []

[code_review_agent.agents.security]
agent_id = "c62142f5-3992-476d-9131-bf85e1beffb7"
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.9              # Threshold of confidence_score for a comment to qualify to be made on PR

[code_review_agent.agents.code_communication]
agent_id = "36b9b529-3ad4-4ddf-9a12-8537ea9765a8"
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.98

[code_review_agent.agents.performance_optimisation]
agent_id = "5932a405-96cb-4508-bfd4-443397583f95"
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.9

[code_review_agent.agents.code_maintainability]
agent_id = "ccfe1b06-f5f2-42b1-a209-4d560edbd5f4"
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.9

[code_review_agent.agents.error]
agent_id = "4a3f593d-73cd-41d6-85a0-dc96c17ce9bb"
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.9

[code_review_agent.agents.business_logic_validation]
agent_id = "9fa43db8-4a3d-43e8-95c0-de96ed58e606"
enable = true
custom_prompt = ""
is_override = true
confidence_score = 0.9

[chat]
enable = true
model = "gpt-4o"
is_override = true
custom_prompt = ""

[pr_summary]
agent_id = "294c1355-38c7-4f69-8914-c95c92e16dbb"
enable = true
model = "gpt-4o"
is_override = true
custom_prompt = ""
