import pandas as pd

data = data = [
    [2, 6824, "SECURITY", "security"],
    [1, 4056, "MAINTAINABILITY", "code_maintainability"],
    [16, 3679, "USER_STORY", "business_validation_agent"],
    [15, 3343, "CODE_QUALITY", "code_maintainability"],
    [12, 3269, "CODE_ROBUSTNESS", "code_maintainability"],
    [32, 2883, "RUNTIME_ERROR", "error"],
    [27, 2506, "SEMANTIC", "error"],
    [13, 2005, "PERFORMANCE", "performance_optimisation"],
    [11, 1912, "ERROR", "error"],
    [17, 1869, "READABILITY", "code_maintainability"],
    [30, 1726, "RUNTIME", ""],
    [33, 752, "SEMANTIC_ERROR", ""],
    [4, 680, "DOCSTRING", "code_communication"],
    [18, 587, "REUSABILITY", "code_maintainability"],
    [10, 537, "DATABASE_PERFORMANCE", "performance_optimisation"],
    [8, 461, "ALGORITHM_EFFICIENCY", "performance_optimisation"],
    [6, 321, "ARCHITECTURE", "code_maintainability"],
    [19, 315, "LOGICAL_ERROR", "error"],
    [29, 239, "LOGICAL", ""],
    [37, 177, "EDGE_CASE", ""],
    [31, 166, "SYNTAX", ""],
    [3, 165, "DOCUMENTATION", "code_communication"],
    [53, 116, "{ERROR}", "error"],
    [14, 104, "LOGGING", "code_communication"],
    [35, 102, "IMPROVEMENT", ""],
    [20, 65, "SYNTAX_ERROR", "error"],
    [43, 49, "EDGE_CASES", ""],
    [5, 33, "TESTING", "code_maintainability"],
    [57, 22, "CLEANUP", ""],
    [28, 22, "{SECURITY}", "security"],
    [51, 16, "ENHANCEMENT", ""],
    [58, 16, "FEATURE", ""],
    [34, 9, "INFO", ""],
    [26, 8, "ACCESSIBILITY", ""],
    [24, 8, "BUSINESS_LOGIC", "business_validation_agent"],
    [38, 8, "STYLE", ""],
    [7, 8, "DEPENDENCIES", ""],
    [46, 7, "LOGIC", ""],
    [63, 6, "LOGIC_ERROR", "error"],
    [45, 6, "REMOVED", ""],
    [54, 6, "OPTIMIZATION", ""],
    [55, 6, "ERROR_HANDLING", "error"],
    [69, 5, "API_CHANGE", ""],
    [23, 4, "VALID_IMPLEMENTATION", ""],
    [80, 4, "REFACTOR", ""],
    [59, 4, "INFORMATIONAL", ""],
    [9, 4, "RESOURCE_MANAGEMENT", "performance_optimisation"],
    [71, 4, "BEST_PRACTICE", ""],
    [47, 4, "VALID", ""],
    [68, 3, "LAYOUT", ""],
    [52, 3, "RESOLVED", ""],
    [60, 3, "VISUAL", ""],
    [65, 3, "WARNING", ""],
    [66, 2, "BEST_PRACTICES", "code_maintainability"],
    [82, 2, "CODE ROBUSTNESS", "code_maintainability"],
    [48, 2, "RUNTIMEERROR", "error"],
    [81, 2, "CODE COMMUNICATION", ""],
    [67, 2, "CONFIGURATION", ""],
    [83, 2, "DEPENDENCY", ""],
    [41, 2, "CORRECT_IMPLEMENTATION", ""],
    [62, 2, "{INFO}", ""],
    [77, 2, "SECURITY_ERROR", "security"],
    [73, 2, "{RUNTIME_ERROR}", "error"],
    [39, 2, "RUNTIME_ERRORS", "error"],
    [21, 2, "NAMING_CONVENTIONS", ""],
    [89, 1, "SEMANTIC ERROR", "error"],
    [93, 1, "SECURITY_-_ALWAYS_THIS_VALUE_SINCE_ITS_A_SECURITY_AGENT", "security"],
    [61, 1, "UNUSED_CODE", ""],
    [92, 1, "UI", ""],
    [25, 1, "TEST_QUALITY", "code_maintainability"],
    [49, 1, "SEMANTICERROR", "error"],
    [84, 1, "CONFIG", ""],
    [86, 1, "LOCALIZATION", ""],
    [90, 1, "CORRECT", ""],
    [70, 1, "TYPE_SAFETY", ""],
    [96, 1, "CODE_STYLE", "code_maintainability"],
    [74, 1, "IMPACT", ""],
    [76, 1, "DEPENDENCY_UPDATE", ""],
    [87, 1, "TODO", ""],
    [42, 1, "MAINTENANCE", ""],
    [56, 1, "CONFIGURATION_ERROR", ""],
    [88, 1, "RUNTIME ERROR", "error"],
    [44, 1, "UNUSED_VARIABLE", ""],
    [40, 1, "SEMANTIC_ERRORS", "error"],
    [98, 1, "ALGORITHMIC_EFFICIENCY", "performance_optimisation"],
    [75, 1, "COMMENT", ""],
    [22, 1, "USER_EXPERIENCE", ""],
    [97, 1, "BREAKING_CHANGE", "error"],
    [50, 1, "CONFIGURATION_UPDATE", ""],
    [36, 1, "NO_ERROR", ""],
    [72, 1, "CLEAN_CODE", ""],
    [95, 1, "COMPATIBILITY", "error"],
]


df = pd.DataFrame(data, columns=["bucket_id", "count", "name", "agent"])
df.to_csv("bucket_data.csv", index=False)
