from deputydev_core.llm_handler.models.dto.message_thread_dto import LLModels

from .claude_3_point_7_sonnet import Claude3Point7CodeCommunicationCommentsGenerationPrompt


class Claude4CodeCommunicationCommentsGenerationPrompt(Claude3Point7CodeCommunicationCommentsGenerationPrompt):
    model_name = LLModels.CLAUDE_4_SONNET
