from .claude_3_point_5_sonnet import Claude3Point5CustomAgentCommentGenerationPrompt


class Claude3Point7CodeMaintainabilityCommentsGenerationPass2Prompt(Claude3Point5CustomAgentCommentGenerationPrompt):
    pass
