from deputydev_core.llm_handler.models.dto.message_thread_dto import LLModels

from .claude_3_point_7_sonnet import Claude3Point7ErrorCommentsGenerationPass1Prompt


class Claude4ErrorCommentsGenerationPass1Prompt(Claude3Point7ErrorCommentsGenerationPass1Prompt):
    model_name = LLModels.CLAUDE_4_SONNET
