from enum import Enum


class PromptFeatures(Enum):
    SECURITY_COMMENTS_GENERATION_PASS_1 = "SECURITY_COMMENTS_GENERATION_PASS_1"
    SECURITY_COMMENTS_GENERATION_PASS_2 = "SECURITY_COMMENTS_GENERATION_PASS_2"
    CODE_COMMUNICATION_COMMENTS_GENERATION_PASS_1 = "CODE_COMMUNICATION_COMMENTS_GENERATION_PASS_1"
    CODE_COMMUNICATION_COMMENTS_GENERATION_PASS_2 = "CODE_COMMUNICATION_COMMENTS_GENERATION_PASS_2"
    PERFORMANCE_OPTIMIZATION_COMMENTS_GENERATION_PASS_1 = "PERFORMANCE_OPTIMIZATION_COMMENTS_GENERATION_PASS_1"
    PERFORMANCE_OPTIMIZATION_COMMENTS_GENERATION_PASS_2 = "PERFORMANCE_OPTIMIZATION_COMMENTS_GENERATION_PASS_2"
    CODE_MAINTAINABILITY_COMMENTS_GENERATION_PASS_1 = "CODE_MAINTAINABILITY_COMMENTS_GENERATION_PASS_1"
    CODE_MAINTAINABILITY_COMMENTS_GENERATION_PASS_2 = "CODE_MAINTAINABILITY_COMMENTS_GENERATION_PASS_2"
    ERROR_COMMENTS_GENERATION_PASS_1 = "ERROR_COMMENTS_GENERATION_PASS_1"
    ERROR_COMMENTS_GENERATION_PASS_2 = "ERROR_COMMENTS_GENERATION_PASS_2"
    BUSINESS_LOGIC_VALIDATION_COMMENTS_GENERATION_PASS_1 = "BUSINESS_LOGIC_VALIDATION_COMMENTS_GENERATION_PASS_1"
    BUSINESS_LOGIC_VALIDATION_COMMENTS_GENERATION_PASS_2 = "BUSINESS_LOGIC_VALIDATION_COMMENTS_GENERATION_PASS_2"
    PR_SUMMARIZATION = "PR_SUMMARIZATION"
    COMMENT_VALIDATION = "COMMENT_VALIDATION"
    COMMENT_SUMMARIZATION = "COMMENT_SUMMARIZATION"
    CUSTOM_AGENT_COMMENTS_GENERATION = "CUSTOM_AGENT_COMMENTS_GENERATION"
