from deputydev_core.llm_handler.models.dto.message_thread_dto import LLModels

from .claude_4_sonnet import Claude4CustomAgentCommentGenerationPrompt


class Claude4Point5CustomAgentCommentGenerationPrompt(Claude4CustomAgentCommentGenerationPrompt):
    model_name = LLModels.CLAUDE_4_POINT_5_SONNET
