from enum import Enum


class PromptFeatures(Enum):
    CODE_GENERATION = "CODE_GENERATION"
    CODE_REVIEW = "CODE_REVIEW"
    RE_RANKING = "RE_RANKING"
    TEST_GENERATION = "TEST_GENERATION"
    DOCS_GENERATION = "DOCS_GENERATION"
    TASK_PLANNER = "TASK_PLANNER"
    ITERATIVE_CODE_CHAT = "ITERATIVE_CODE_CHAT"
    DIFF_CREATION = "DIFF_CREATION"
    PLAN_CODE_GENERATION = "PLAN_CODE_GENERATION"
    CHAT_RERANKING = "CHAT_RERANKING"
