from .claude_3_point_5_sonnet import Claude3Point5SecurityCommentsGenerationPass2Prompt


class Claude3Point7SecurityCommentsGenerationPass2Prompt(Claude3Point5SecurityCommentsGenerationPass2Prompt):
    pass
