name: Code Quality

permissions:
  contents: read

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  pre-commit:
    name: Run pre-commit on PR changes to master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history into deputydev_backend
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: deputydev_backend

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit on changed files
        run: |
          cd deputydev_backend
          BASE_REF="origin/${{ github.base_ref }}"
          HEAD_REF="HEAD"
          echo "Running pre-commit from $BASE_REF to $HEAD_REF"
          pre-commit run --from-ref "$BASE_REF" --to-ref "$HEAD_REF"
