name: Tests

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [master]

jobs:
  tests:
    name: Run pytest with uv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies (including dev)
        run: uv sync --all-extras --dev

      - name: Run pytest with coverage
        run: |
          uv run pytest --cov=app --cov-report=term-missing
